#!/bin/sh

case "$1" in
    start)
        ip link set eth0 up
        ip addr flush dev eth0
        ip addr add 10.90.50.44/24 dev eth0
        ;;
    stop)
        ip addr flush dev eth0
        ip link set eth0 down
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac
